require("prototypes.categories")
-- require("prototypes.technology")
-- require("prototypes.refining.items")
-- require("prototypes.refining.recipes")
-- require("prototypes.smelting.items")
-- require("prototypes.smelting.recipes")
require("prototypes.manufacturing.items")
require("prototypes.manufacturing.recipes")
-- require("prototypes.entities.combustion-turbine")
-- require("prototypes.entities.metallurgic-smelter")
-- require("prototypes.entities.electronics-fabricator")
require("prototypes.entities.chip-shooter")
